version: "3.8"
services:
  bpp_webhook:
    build: .
    container_name: bpp_webhook_app
    ports:
      - "8080:8080"
    volumes:
      # This syncs the local code with the container, so changes are reflected instantly
      - .:/usr/src/app
    env_file: ./.env
    networks:
      - local-beckn-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch_local
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false
      # Use this to increase mem to 1gig
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    networks:
      - local-beckn-net

networks:
  local-beckn-net:
    driver: bridge
